# SonarCloud Configuration
sonar.projectKey=payment-transaction-service
sonar.organization=fintech-platform-benas
sonar.projectName=Payment Transaction Service
sonar.projectVersion=1.0.0

# Source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java version
sonar.java.source=17
sonar.java.target=17

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports

# Exclusions (no analizar archivos generados)
sonar.exclusions=\
  **/target/**,\
  **/*MapperImpl.java,\
  **/*Application.java,\
  **/config/**,\
  **/dto/**

# Test exclusions
sonar.test.exclusions=\
  **/test/**,\
  **/*Test.java

# Duplications
sonar.cpd.exclusions=**/dto/**, **/entity/**

# Quality Gate (ajustado realista)
sonar.qualitygate.wait=true
